name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Prepare env and files
        run: |
          mkdir -p data
          cat > .env <<'EOF'
          HOST=127.0.0.1
          PORT=8010
          DATABASE_URL=sqlite:///erp_ci.db
          PYTHONPATH=.
          EOF
          chmod +x scripts/run.sh

      - name: Start API via run.sh (background) and wait until ready
        run: |
          bash scripts/run.sh > uvicorn.log 2>&1 &
          # espera a que /session/open responda 200
          for i in {1..40}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://127.0.0.1:8010/session/open \
              -H 'Content-Type: application/json' --data '{"operator":"demo"}' || true)
            if [ "$CODE" = "200" ]; then
              echo "API ready"
              break
            fi
            sleep 1
          done
          if [ "$CODE" != "200" ]; then
            echo "::error::API did not become ready"
            echo "---- uvicorn.log ----"
            sed -n '1,200p' uvicorn.log || true
            exit 1
          fi

      - name: Run pytest
        env:
          ERP_BASE_URL: http://127.0.0.1:8010
          TEST_COUPON: TEST10
        run: pytest -q -ra

      - name: Upload server logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: uvicorn-log
          path: uvicorn.log
