name: CI
on:
  push:
    branches: [develop, feature/**]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
    
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || true
    
      - name: Lint & format (pre-commit)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true   # avisa pero NO bloquea la build
    
      - name: Run tests
        run: pytest -q
