name: CI
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [feature/**]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || true

      - name: Run pre-commit (ruff/black/etc)
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: pytest -q
