name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Create .env for CI
        run: |
          cat > .env <<'EOF'
          HOST=127.0.0.1
          PORT=8010
          DATABASE_URL=sqlite:///erp.db
          PYTHONPATH=.
          EOF
      - name: Start API (background)
        run: |
          nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8010 > uvicorn.log 2>&1 &
          sleep 2
      - name: Run tests
        env:
          ERP_BASE_URL: http://127.0.0.1:8010
          TEST_COUPON: TEST10
        run: pytest -q
