name: CI

on:
  push:
    branches: [develop, feature/**]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest requests
      - name: Start API (background)
        run: |
          python -m uvicorn app.main:app --host 127.0.0.1 --port 8010 --log-level warning &
          echo $! > uvicorn.pid
        env:
          PYTHONPATH: .
  
      - name: Wait for /health
        run: |
          for i in {1..40}; do
            if curl -fsS http://127.0.0.1:8010/health > /dev/null; then
              echo "API ready"; exit 0
            fi
            sleep 1
          done
          echo "API did not start in time" >&2; exit 1
  
      - name: Run tests
        run: pytest -q

